spring.application.name=backend

#Database

spring.datasource.url=jdbc:mysql://localhost:3306/bazaarHub
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cache.type=redis
spring.cache.cache-names=user
spring.cache.redis.time-to-live=10m
spring.cache.redis.cache-null-values=false

