export enum Role {
  ADMIN = 'ADMIN',
  VENDOR = 'VENDOR',
  CUSTOMER = 'CUSTOMER',
  VISITOR = 'VISITOR',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum OrderStatus {
  SUCCESS = 'SUCCESS',
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentStatus {
  SUCCESS = 'SUCCESS',
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum ProductStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DELETED = 'DELETED',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  DELETED = 'DELETED',
}

export enum CategoryStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DELETED = 'DELETED',
}

export enum ApprovalStatus {
  APPROVED = 'APPROVED',
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
}

export enum CartItemStatus {
  AVAILABLE = 'AVAILABLE',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  LIMITED_STOCK = 'LIMITED_STOCK',
  PRICE_CHANGED = 'PRICE_CHANGED',
  PRODUCT_INACTIVE = 'PRODUCT_INACTIVE',
}

export enum NotificationType {
  ORDER_PLACED = 'ORDER_PLACED',
  ORDER_RECEIVED = 'ORDER_RECEIVED',
  ORDER_STATUS_UPDATED = 'ORDER_STATUS_UPDATED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  VENDOR_APPROVED = 'VENDOR_APPROVED',
  VENDOR_REJECTED = 'VENDOR_REJECTED',
}

export enum Province {
  KOSHI = 'KOSHI',
  MADHESH = 'MADHESH',
  BAGMATI = 'BAGMATI',
  GANDAKI = 'GANDAKI',
  LUMBINI = 'LUMBINI',
  KARNALI = 'KARNALI',
  SUDURPASHCHIM = 'SUDURPASHCHIM',
}

export enum District {
  // Koshi Province
  TAPLEJUNG = 'TAPLEJUNG',
  PANCHTHAR = 'PANCHTHAR',
  ILAM = 'ILAM',
  JHAPA = 'JHAPA',
  MORANG = 'MORANG',
  SUNSARI = 'SUNSARI',
  DHANKUTA = 'DHANKUTA',
  TERHATHUM = 'TERHATHUM',
  SANKHUWASABHA = 'SANKHUWASABHA',
  BHOJPUR = 'BHOJPUR',
  SOLUKHUMBU = 'SOLUKHUMBU',
  OKHALDHUNGA = 'OKHALDHUNGA',
  KHOTANG = 'KHOTANG',
  UDAYAPUR = 'UDAYAPUR',
  // Madhesh Province
  SAPTARI = 'SAPTARI',
  SIRAHA = 'SIRAHA',
  DHANUSHA = 'DHANUSHA',
  MAHOTTARI = 'MAHOTTARI',
  SARLAHI = 'SARLAHI',
  RAUTAHAT = 'RAUTAHAT',
  BARA = 'BARA',
  PARSA = 'PARSA',
  // Bagmati Province
  SINDHULI = 'SINDHULI',
  RAMECHHAP = 'RAMECHHAP',
  DOLAKHA = 'DOLAKHA',
  SINDHUPALCHOK = 'SINDHUPALCHOK',
  KAVREPALANCHOK = 'KAVREPALANCHOK',
  LALITPUR = 'LALITPUR',
  BHAKTAPUR = 'BHAKTAPUR',
  KATHMANDU = 'KATHMANDU',
  NUWAKOT = 'NUWAKOT',
  RASUWA = 'RASUWA',
  DHADING = 'DHADING',
  MAKWANPUR = 'MAKWANPUR',
  CHITWAN = 'CHITWAN',
  // Gandaki Province
  GORKHA = 'GORKHA',
  MANANG = 'MANANG',
  MUSTANG = 'MUSTANG',
  MYAGDI = 'MYAGDI',
  KASKI = 'KASKI',
  LAMJUNG = 'LAMJUNG',
  TANAHU = 'TANAHU',
  NAWALPUR = 'NAWALPUR',
  SYANGJA = 'SYANGJA',
  PARBAT = 'PARBAT',
  BAGLUNG = 'BAGLUNG',
  // Lumbini Province
  GULMI = 'GULMI',
  PALPA = 'PALPA',
  ARGHAKHANCHI = 'ARGHAKHANCHI',
  KAPILVASTU = 'KAPILVASTU',
  RUPANDEHI = 'RUPANDEHI',
  NAWALPARASI_WEST = 'NAWALPARASI_WEST',
  PYUTHAN = 'PYUTHAN',
  ROLPA = 'ROLPA',
  EASTERN_RUKUM = 'EASTERN_RUKUM',
  DANG = 'DANG',
  BANKE = 'BANKE',
  BARDIYA = 'BARDIYA',
  // Karnali Province
  DOLPA = 'DOLPA',
  MUGU = 'MUGU',
  HUMLA = 'HUMLA',
  JUMLA = 'JUMLA',
  KALIKOT = 'KALIKOT',
  DAILEKH = 'DAILEKH',
  JAJARKOT = 'JAJARKOT',
  WESTERN_RUKUM = 'WESTERN_RUKUM',
  SALYAN = 'SALYAN',
  SURKHET = 'SURKHET',
  // Sudurpashchim Province
  BAJURA = 'BAJURA',
  BAJHANG = 'BAJHANG',
  ACHHAM = 'ACHHAM',
  DOTI = 'DOTI',
  KAILALI = 'KAILALI',
  KANCHANPUR = 'KANCHANPUR',
  DADELDHURA = 'DADELDHURA',
  BAITADI = 'BAITADI',
  DARCHULA = 'DARCHULA',
}

export enum Municipality {
  // Kathmandu District
  KATHMANDU_METROPOLITAN_CITY = 'KATHMANDU_METROPOLITAN_CITY',
  LALITPUR_METROPOLITAN_CITY = 'LALITPUR_METROPOLITAN_CITY',
  BHAKTAPUR_MUNICIPALITY = 'BHAKTAPUR_MUNICIPALITY',
  MADHYAPUR_THIMI_MUNICIPALITY = 'MADHYAPUR_THIMI_MUNICIPALITY',
  KIRTIPUR_MUNICIPALITY = 'KIRTIPUR_MUNICIPALITY',
  BUDHANILKANTHA_MUNICIPALITY = 'BUDHANILKANTHA_MUNICIPALITY',
  GOKARNESHWAR_MUNICIPALITY = 'GOKARNESHWAR_MUNICIPALITY',
  KAGESHWORI_MANOHARA_MUNICIPALITY = 'KAGESHWORI_MANOHARA_MUNICIPALITY',
  NAGARJUN_MUNICIPALITY = 'NAGARJUN_MUNICIPALITY',
  SHANKARAPUR_MUNICIPALITY = 'SHANKARAPUR_MUNICIPALITY',
  TARAKESHWAR_MUNICIPALITY = 'TARAKESHWAR_MUNICIPALITY',
  TOKHA_MUNICIPALITY = 'TOKHA_MUNICIPALITY',
  CHANDRAGIRI_MUNICIPALITY = 'CHANDRAGIRI_MUNICIPALITY',
  DAKSHINKALI_MUNICIPALITY = 'DAKSHINKALI_MUNICIPALITY',
  // Lalitpur District
  GODAWARI_MUNICIPALITY = 'GODAWARI_MUNICIPALITY',
  MAHALAXMI_MUNICIPALITY = 'MAHALAXMI_MUNICIPALITY',
  KONJYOSOM_RURAL_MUNICIPALITY = 'KONJYOSOM_RURAL_MUNICIPALITY',
  BAGMATI_RURAL_MUNICIPALITY = 'BAGMATI_RURAL_MUNICIPALITY',
  // Kaski District (Pokhara)
  POKHARA_METROPOLITAN_CITY = 'POKHARA_METROPOLITAN_CITY',
  ANNAPURNA_RURAL_MUNICIPALITY = 'ANNAPURNA_RURAL_MUNICIPALITY',
  MACHHAPUCHCHHRE_RURAL_MUNICIPALITY = 'MACHHAPUCHCHHRE_RURAL_MUNICIPALITY',
  MADI_RURAL_MUNICIPALITY = 'MADI_RURAL_MUNICIPALITY',
  RUPA_RURAL_MUNICIPALITY = 'RUPA_RURAL_MUNICIPALITY',
  // Chitwan District
  BHARATPUR_METROPOLITAN_CITY = 'BHARATPUR_METROPOLITAN_CITY',
  RATNANAGAR_MUNICIPALITY = 'RATNANAGAR_MUNICIPALITY',
  RAPTI_MUNICIPALITY = 'RAPTI_MUNICIPALITY',
  ICHCHHAKAMANA_RURAL_MUNICIPALITY = 'ICHCHHAKAMANA_RURAL_MUNICIPALITY',
  KALIKA_MUNICIPALITY = 'KALIKA_MUNICIPALITY',
  KHAIRAHANI_MUNICIPALITY = 'KHAIRAHANI_MUNICIPALITY',
  // Rupandehi District (Butwal)
  BUTWAL_SUBMETROPOLITAN_CITY = 'BUTWAL_SUBMETROPOLITAN_CITY',
  DEVDAHA_MUNICIPALITY = 'DEVDAHA_MUNICIPALITY',
  LUMBINI_SANSKRITI_MUNICIPALITY = 'LUMBINI_SANSKRITI_MUNICIPALITY',
  MARCHAWARI_RURAL_MUNICIPALITY = 'MARCHAWARI_RURAL_MUNICIPALITY',
  MAYA_DEVI_RURAL_MUNICIPALITY = 'MAYA_DEVI_RURAL_MUNICIPALITY',
  OMSATIYA_RURAL_MUNICIPALITY = 'OMSATIYA_RURAL_MUNICIPALITY',
  ROHINI_RURAL_MUNICIPALITY = 'ROHINI_RURAL_MUNICIPALITY',
  SAMMARIMAI_RURAL_MUNICIPALITY = 'SAMMARIMAI_RURAL_MUNICIPALITY',
  SHUDHODHAN_RURAL_MUNICIPALITY = 'SHUDHODHAN_RURAL_MUNICIPALITY',
  SIYARI_RURAL_MUNICIPALITY = 'SIYARI_RURAL_MUNICIPALITY',
  TILOTTAMA_MUNICIPALITY = 'TILOTTAMA_MUNICIPALITY',
  // Morang District (Biratnagar)
  BIRATNAGAR_METROPOLITAN_CITY = 'BIRATNAGAR_METROPOLITAN_CITY',
  URLABARI_MUNICIPALITY = 'URLABARI_MUNICIPALITY',
  SUNDARHARAICHA_MUNICIPALITY = 'SUNDARHARAICHA_MUNICIPALITY',
  LETANG_MUNICIPALITY = 'LETANG_MUNICIPALITY',
  PATHARI_SHANISHCHARE_MUNICIPALITY = 'PATHARI_SHANISHCHARE_MUNICIPALITY',
  RANGELI_MUNICIPALITY = 'RANGELI_MUNICIPALITY',
  RATUWAMAI_RURAL_MUNICIPALITY = 'RATUWAMAI_RURAL_MUNICIPALITY',
  MIKLAJUNG_RURAL_MUNICIPALITY = 'MIKLAJUNG_RURAL_MUNICIPALITY',
  DHANPALTHAN_RURAL_MUNICIPALITY = 'DHANPALTHAN_RURAL_MUNICIPALITY',
  GRAMTHAN_RURAL_MUNICIPALITY = 'GRAMTHAN_RURAL_MUNICIPALITY',
  BELBARI_MUNICIPALITY = 'BELBARI_MUNICIPALITY',
  // Sunsari District
  DHARAN_SUBMETROPOLITAN_CITY = 'DHARAN_SUBMETROPOLITAN_CITY',
  ITAHARI_SUBMETROPOLITAN_CITY = 'ITAHARI_SUBMETROPOLITAN_CITY',
  INARUWA_MUNICIPALITY = 'INARUWA_MUNICIPALITY',
  RAMDHUNI_MUNICIPALITY = 'RAMDHUNI_MUNICIPALITY',
  BARAHAKSHETRA_MUNICIPALITY = 'BARAHAKSHETRA_MUNICIPALITY',
  HARINAGARA_RURAL_MUNICIPALITY = 'HARINAGARA_RURAL_MUNICIPALITY',
  BHOKRAHA_NARSINGH_RURAL_MUNICIPALITY = 'BHOKRAHA_NARSINGH_RURAL_MUNICIPALITY',
  KOSHI_RURAL_MUNICIPALITY = 'KOSHI_RURAL_MUNICIPALITY',
  GADHI_RURAL_MUNICIPALITY = 'GADHI_RURAL_MUNICIPALITY',
  // Bara District
  KALAIYA_SUBMETROPOLITAN_CITY = 'KALAIYA_SUBMETROPOLITAN_CITY',
  NIJGADH_MUNICIPALITY = 'NIJGADH_MUNICIPALITY',
  JITPUR_SIMARA_SUBMETROPOLITAN_CITY = 'JITPUR_SIMARA_SUBMETROPOLITAN_CITY',
  SIMRAUNGADH_MUNICIPALITY = 'SIMRAUNGADH_MUNICIPALITY',
  MAHAGADHIMAI_MUNICIPALITY = 'MAHAGADHIMAI_MUNICIPALITY',
  PARWANIPUR_RURAL_MUNICIPALITY = 'PARWANIPUR_RURAL_MUNICIPALITY',
  PHETA_RURAL_MUNICIPALITY = 'PHETA_RURAL_MUNICIPALITY',
  PRASAUNI_RURAL_MUNICIPALITY = 'PRASAUNI_RURAL_MUNICIPALITY',
  SUWARNA_MUNICIPALITY = 'SUWARNA_MUNICIPALITY',
  ADARSHA_KOTWAL_RURAL_MUNICIPALITY = 'ADARSHA_KOTWAL_RURAL_MUNICIPALITY',
  BARAGADHI_RURAL_MUNICIPALITY = 'BARAGADHI_RURAL_MUNICIPALITY',
  BAWANIPUR_RURAL_MUNICIPALITY = 'BAWANIPUR_RURAL_MUNICIPALITY',
  BISHRAMPUR_RURAL_MUNICIPALITY = 'BISHRAMPUR_RURAL_MUNICIPALITY',
  DEVTAL_RURAL_MUNICIPALITY = 'DEVTAL_RURAL_MUNICIPALITY',
  KAUDENA_RURAL_MUNICIPALITY = 'KAUDENA_RURAL_MUNICIPALITY',
  KOILABI_RURAL_MUNICIPALITY = 'KOILABI_RURAL_MUNICIPALITY',
  // Banke District (Nepalgunj)
  NEPALGUNJ_SUBMETROPOLITAN_CITY = 'NEPALGUNJ_SUBMETROPOLITAN_CITY',
  KOHALPUR_MUNICIPALITY = 'KOHALPUR_MUNICIPALITY',
  DUDUWA_RURAL_MUNICIPALITY = 'DUDUWA_RURAL_MUNICIPALITY',
  JANKI_RURAL_MUNICIPALITY = 'JANKI_RURAL_MUNICIPALITY',
  KHAJURA_RURAL_MUNICIPALITY = 'KHAJURA_RURAL_MUNICIPALITY',
  NARAINAPUR_RURAL_MUNICIPALITY = 'NARAINAPUR_RURAL_MUNICIPALITY',
  RAPTI_SONARI_RURAL_MUNICIPALITY = 'RAPTI_SONARI_RURAL_MUNICIPALITY',
  // Kailali District (Dhangadhi)
  DHANGADHI_SUBMETROPOLITAN_CITY = 'DHANGADHI_SUBMETROPOLITAN_CITY',
  TIKAPUR_MUNICIPALITY = 'TIKAPUR_MUNICIPALITY',
  BHAJANI_MUNICIPALITY = 'BHAJANI_MUNICIPALITY',
  GHODAGHODI_MUNICIPALITY = 'GHODAGHODI_MUNICIPALITY',
  BARDAGORIYA_RURAL_MUNICIPALITY = 'BARDAGORIYA_RURAL_MUNICIPALITY',
  CHURE_RURAL_MUNICIPALITY = 'CHURE_RURAL_MUNICIPALITY',
  DOGDAKEDAR_RURAL_MUNICIPALITY = 'DOGDAKEDAR_RURAL_MUNICIPALITY',
  JANAKI_RURAL_MUNICIPALITY = 'JANAKI_RURAL_MUNICIPALITY',
  JOSHIPUR_RURAL_MUNICIPALITY = 'JOSHIPUR_RURAL_MUNICIPALITY',
  KAILARI_RURAL_MUNICIPALITY = 'KAILARI_RURAL_MUNICIPALITY',
  LAMKI_CHUHA_MUNICIPALITY = 'LAMKI_CHUHA_MUNICIPALITY',
  MOHANYAL_RURAL_MUNICIPALITY = 'MOHANYAL_RURAL_MUNICIPALITY',
  PHULBARI_MUNICIPALITY = 'PHULBARI_MUNICIPALITY',
  // Jhapa District
  BHADRAPUR_MUNICIPALITY = 'BHADRAPUR_MUNICIPALITY',
  BIRTAMOD_MUNICIPALITY = 'BIRTAMOD_MUNICIPALITY',
  DAMAK_MUNICIPALITY = 'DAMAK_MUNICIPALITY',
  GAURADAHA_MUNICIPALITY = 'GAURADAHA_MUNICIPALITY',
  KANKAI_MUNICIPALITY = 'KANKAI_MUNICIPALITY',
  MECHINAGAR_MUNICIPALITY = 'MECHINAGAR_MUNICIPALITY',
  SHIVASATAXI_RURAL_MUNICIPALITY = 'SHIVASATAXI_RURAL_MUNICIPALITY',
  // Other
  OTHER = 'OTHER',
}
