package com.bazaarhub.backend.shared.enums;

public enum District {


    TAPLEJUNG, PANCHTHAR, ILAM, JHAPA, MORANG, SUNSARI,
    DHANKUTA, TERHATHUM, SANKHUWASABHA, BHOJPUR, SOLUKHUMBU,
    OKHALDHUNGA, KHOTANG, UDAYAPUR,

    // Madhesh Province
    SAPTARI, SIRAHA, DHANUSHA, MAHOTTARI, SARLAHI,
    RAUTAHAT, BARA, PARSA,

    // Bagmati Province
    SINDHULI, RAMECHHAP, DOLAKHA, SINDHUPALCHOK, KAVREPALANCHOK,
    LALITPUR, BHAKTAPUR, KATHMANDU, NUWAKOT, RASUWA,
    DHADING, MAKWANPUR, CHITWAN,

    // Gandaki Province
    GORKHA, MANANG, MUSTANG, MYAGDI, KASKI, LAMJUNG,
    TANAHU, NAWALPUR, SYANGJA, PARBAT, BAGLUNG,

    // Lumbini Province
    GULMI, PALPA, ARGHAKHANCHI, KAPILVASTU, RUPANDEHI,
    NAWALPARASI_WEST, PYUTHAN, ROLPA, EASTERN_RUKUM, DANG, BANKE, BARDIYA,

    // Karnali Province
    DOLPA, MUGU, HUMLA, JUMLA, KALIKOT, DAILEKH,
    JAJARKOT, WESTERN_RUKUM, SALYAN, SURKHET,

    // Sudurpashchim Province
    BAJURA, BAJHANG, ACHHAM, DOTI, KAILALI, KANCHANPUR,
    DADELDHURA, BAITADI, DARCHULA
}