package com.bazaarhub.backend.shared.enums;

public enum Municipality {

    // Kathmandu District
    KATHMANDU_METROPOLITAN_CITY,
    LALITPUR_METROPOLITAN_CITY,
    BHAKTAPUR_MUNICIPALITY,
    MADHYAPUR_THIMI_MUNICIPALITY,
    KIRTIPUR_MUNICIPALITY,
    BUDHANILKANTHA_MUNICIPALITY,
    GOKARNESHWAR_MUNICIPALITY,
    KAGESHWORI_MANOHARA_MUNICIPALITY,
    NAGARJUN_MUNICIPALITY,
    SHANKARAPUR_MUNICIPALITY,
    TARAKESHWAR_MUNICIPALITY,
    TOKHA_MUNICIPALITY,
    CHANDRAGIRI_MUNICIPALITY,
    DAKSHINKALI_MUNICIPALITY,

    // Lalitpur District
    GODAWARI_MUNICIPALITY,
    MAHALAXMI_MUNICIPALITY,
    KONJYOSOM_RURAL_MUNICIPALITY,
    BAGMATI_RURAL_MUNICIPALITY,

    // Kaski District (Pokhara)
    POKHARA_METROPOLITAN_CITY,
    ANNAPURNA_RURAL_MUNICIPALITY,
    MACHHAPUCHCHHRE_RURAL_MUNICIPALITY,
    MADI_RURAL_MUNICIPALITY,
    RUPA_RURAL_MUNICIPALITY,

    // Chitwan District
    BHARATPUR_METROPOLITAN_CITY,
    RATNANAGAR_MUNICIPALITY,
    RAPTI_MUNICIPALITY,
    ICHCHHAKAMANA_RURAL_MUNICIPALITY,
    KALIKA_MUNICIPALITY,
    KHAIRAHANI_MUNICIPALITY,

    // Rupandehi District (Butwal)
    BUTWAL_SUBMETROPOLITAN_CITY,
    DEVDAHA_MUNICIPALITY,
    LUMBINI_SANSKRITI_MUNICIPALITY,
    MARCHAWARI_RURAL_MUNICIPALITY,
    MAYA_DEVI_RURAL_MUNICIPALITY,
    OMSATIYA_RURAL_MUNICIPALITY,
    ROHINI_RURAL_MUNICIPALITY,
    SAMMARIMAI_RURAL_MUNICIPALITY,
    SHUDHODHAN_RURAL_MUNICIPALITY,
    SIYARI_RURAL_MUNICIPALITY,
    TILOTTAMA_MUNICIPALITY,

    // Morang District (Biratnagar)
    BIRATNAGAR_METROPOLITAN_CITY,
    URLABARI_MUNICIPALITY,
    SUNDARHARAICHA_MUNICIPALITY,
    LETANG_MUNICIPALITY,
    PATHARI_SHANISHCHARE_MUNICIPALITY,
    RANGELI_MUNICIPALITY,
    RATUWAMAI_RURAL_MUNICIPALITY,
    MIKLAJUNG_RURAL_MUNICIPALITY,
    DHANPALTHAN_RURAL_MUNICIPALITY,
    GRAMTHAN_RURAL_MUNICIPALITY,
    BELBARI_MUNICIPALITY,

    // Sunsari District (Dharan/Itahari)
    DHARAN_SUBMETROPOLITAN_CITY,
    ITAHARI_SUBMETROPOLITAN_CITY,
    INARUWA_MUNICIPALITY,
    RAMDHUNI_MUNICIPALITY,
    BARAHAKSHETRA_MUNICIPALITY,
    HARINAGARA_RURAL_MUNICIPALITY,
    BHOKRAHA_NARSINGH_RURAL_MUNICIPALITY,
    KOSHI_RURAL_MUNICIPALITY,
    GADHI_RURAL_MUNICIPALITY,

    // Bara District
    KALAIYA_SUBMETROPOLITAN_CITY,
    NIJGADH_MUNICIPALITY,
    JITPUR_SIMARA_SUBMETROPOLITAN_CITY,
    SIMRAUNGADH_MUNICIPALITY,
    MAHAGADHIMAI_MUNICIPALITY,
    PARWANIPUR_RURAL_MUNICIPALITY,
    PHETA_RURAL_MUNICIPALITY,
    PRASAUNI_RURAL_MUNICIPALITY,
    SUWARNA_MUNICIPALITY,
    ADARSHA_KOTWAL_RURAL_MUNICIPALITY,
    BARAGADHI_RURAL_MUNICIPALITY,
    BAWANIPUR_RURAL_MUNICIPALITY,
    BISHRAMPUR_RURAL_MUNICIPALITY,
    DEVTAL_RURAL_MUNICIPALITY,
    KAUDENA_RURAL_MUNICIPALITY,
    KOILABI_RURAL_MUNICIPALITY,

    // Banke District (Nepalgunj)
    NEPALGUNJ_SUBMETROPOLITAN_CITY,
    KOHALPUR_MUNICIPALITY,
    DUDUWA_RURAL_MUNICIPALITY,
    JANKI_RURAL_MUNICIPALITY,
    KHAJURA_RURAL_MUNICIPALITY,
    NARAINAPUR_RURAL_MUNICIPALITY,
    RAPTI_SONARI_RURAL_MUNICIPALITY,

    // Kailali District (Dhangadhi)
    DHANGADHI_SUBMETROPOLITAN_CITY,
    TIKAPUR_MUNICIPALITY,
    BHAJANI_MUNICIPALITY,
    GHODAGHODI_MUNICIPALITY,
    BARDAGORIYA_RURAL_MUNICIPALITY,
    CHURE_RURAL_MUNICIPALITY,
    DOGDAKEDAR_RURAL_MUNICIPALITY,
    JANAKI_RURAL_MUNICIPALITY,
    JOSHIPUR_RURAL_MUNICIPALITY,
    KAILARI_RURAL_MUNICIPALITY,
    LAMKI_CHUHA_MUNICIPALITY,
    MOHANYAL_RURAL_MUNICIPALITY,
    PHULBARI_MUNICIPALITY,

    // Jhapa District
    BHADRAPUR_MUNICIPALITY,
    BIRTAMOD_MUNICIPALITY,
    DAMAK_MUNICIPALITY,
    GAURADAHA_MUNICIPALITY,
    KANKAI_MUNICIPALITY,
    MECHINAGAR_MUNICIPALITY,
    SHIVASATAXI_RURAL_MUNICIPALITY,

    // Other
    OTHER
}